import { TOOL_OPTION_SCHEMAS } from "./options";
import { TOOL_SEO } from "./seo";
import type { ToolDefinition, ToolSlug } from "./types";

export const tools = [
  {
    route: { slug: "merge-videos", path: "/tools/merge-videos" },
    title: "Merge Videos",
    description: "Combine several video clips into one file.",
    icon: "⊕",
    status: "ready",
    input: { kind: "video", accept: "video/*", multiple: true },
    output: { kind: "video", formatLabel: "Video file" },
    analyticsCategory: "combine",
    seo: TOOL_SEO["merge-videos"],
    options: TOOL_OPTION_SCHEMAS["merge-videos"],
  },
  {
    route: { slug: "trim-video", path: "/tools/trim-video" },
    title: "Trim Video",
    description: "Cut the beginning or end of a video quickly.",
    icon: "✂",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "Trimmed video" },
    analyticsCategory: "edit",
    seo: TOOL_SEO["trim-video"],
    options: TOOL_OPTION_SCHEMAS["trim-video"],
  },
  {
    route: { slug: "compress-video", path: "/tools/compress-video" },
    title: "Compress Video",
    description: "Reduce video file size while preserving quality.",
    icon: "⇩",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "Compressed video" },
    analyticsCategory: "optimize",
    seo: TOOL_SEO["compress-video"],
    options: TOOL_OPTION_SCHEMAS["compress-video"],
  },
  {
    route: { slug: "resize-video", path: "/tools/resize-video" },
    title: "Resize for Social Media",
    description: "Resize videos for TikTok, Reels, Shorts and more.",
    icon: "↔",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "Resized video" },
    analyticsCategory: "optimize",
    seo: TOOL_SEO["resize-video"],
    options: TOOL_OPTION_SCHEMAS["resize-video"],
  },
  {
    route: { slug: "remove-audio", path: "/tools/remove-audio" },
    title: "Remove Audio",
    description: "Create a silent copy of your video.",
    icon: "⌁",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "Silent video" },
    analyticsCategory: "audio",
    seo: TOOL_SEO["remove-audio"],
    options: TOOL_OPTION_SCHEMAS["remove-audio"],
  },
  {
    route: { slug: "convert-mp4", path: "/tools/convert-mp4" },
    title: "Convert to MP4",
    description: "Convert common video formats to MP4.",
    icon: "MP4",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "MP4 video" },
    analyticsCategory: "format",
    seo: TOOL_SEO["convert-mp4"],
    options: TOOL_OPTION_SCHEMAS["convert-mp4"],
  },
  {
    route: { slug: "extract-audio", path: "/tools/extract-audio" },
    title: "Extract Audio",
    description: "Save the audio track from a video.",
    icon: "♫",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "audio", formatLabel: "Audio file" },
    analyticsCategory: "audio",
    seo: TOOL_SEO["extract-audio"],
    options: TOOL_OPTION_SCHEMAS["extract-audio"],
  },
  {
    route: { slug: "image-to-video", path: "/tools/image-to-video" },
    title: "Image to Video",
    description: "Turn one or more images into a video.",
    icon: "▣",
    status: "coming-soon",
    input: { kind: "image", accept: "image/*", multiple: true },
    output: { kind: "video", formatLabel: "Video file" },
    analyticsCategory: "create",
    seo: TOOL_SEO["image-to-video"],
    options: TOOL_OPTION_SCHEMAS["image-to-video"],
  },
  {
    route: { slug: "video-speed", path: "/tools/video-speed" },
    title: "Video Speed",
    description: "Speed up or slow down a video.",
    icon: "×2",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "Adjusted video" },
    analyticsCategory: "edit",
    seo: TOOL_SEO["video-speed"],
    options: TOOL_OPTION_SCHEMAS["video-speed"],
  },
  {
    route: { slug: "reverse-video", path: "/tools/reverse-video" },
    title: "Reverse Video",
    description: "Play a video backwards and export it.",
    icon: "↶",
    status: "coming-soon",
    input: { kind: "video", accept: "video/*", multiple: false },
    output: { kind: "video", formatLabel: "Reversed video" },
    analyticsCategory: "edit",
    seo: TOOL_SEO["reverse-video"],
    options: TOOL_OPTION_SCHEMAS["reverse-video"],
  },
] as const satisfies readonly ToolDefinition[];

export function getTool(slug: string): ToolDefinition | undefined {
  return tools.find((tool) => tool.route.slug === slug);
}

export function getToolPath(slug: ToolSlug): `/tools/${ToolSlug}` {
  return `/tools/${slug}`;
}
